// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetModel(): Promise<$models.Model> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3820758837) as any;
    return $resultPromise;
}

export function Quit(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4171797259) as any;
    return $resultPromise;
}
